name: Run Pix Bot (Daily)

on:
  schedule:
    # 21:20 Brasília (UTC-3) => 00:20 UTC (dia seguinte)
    - cron: "20 0 * * *"
    # Retry automático 15 min depois (00:35 UTC => 21:35 BRT)
    - cron: "35 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write   # permite commitar no repositório

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # Força modo HTTP (sem Selenium) no CI
      GITHUB_ACTIONS: "true"
      # Salva/ler o Excel na raiz do repositório
      OUT_DIR: "."

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # garante histórico para commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Se precisar de segredos, use:
      # - name: Export secrets
      #   run: |
      #     echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Run bot (mês padrão ou intervalo)
        run: |
          python bot.py
          # Exemplo para intervalo:
          # python bot.py 202501 202508

      - name: Upload Excel as artifact (backup/consulta)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pix_pordia_xlsx
          path: pix_pordia.xlsx
          if-no-files-found: warn

      - name: Commit updated Excel back to repo
        run: |
          set -e
          if [ -f "pix_pordia.xlsx" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add pix_pordia.xlsx
            # só commita se houver mudança
            if git diff --cached --quiet; then
              echo "Nenhuma mudança no Excel. Nada a commitar."
            else
              git commit -m "Update pix_pordia.xlsx [skip ci]"
              git push
            fi
          else
            echo "Arquivo pix_pordia.xlsx não encontrado para commit."
          fi
